### ISSUE TITLE
ValueError when attempting to install

### ISSUE THREAD

**Issue by Riunix** [haihala/modman#3]
`ValueError: invalid literal for int() with base10: 'gfxtweak'`

When attempting to install mods, I always get this error.  My first attempt at installing contained a mod for Bob's Electronics where the name appearing in the URL ended with '_gfxtweak'.  After deleting the mod from the list of mods to install I still get the same error.  When attempting on a fresh copy, still get the same error.

**Comment by Riunix** [comment]
Problem comes from having a mod with multiple underscores (i.e. "random_mod_1.5") already installed within the mods folder

**Comment by Riunix** [comment]
In cache.py, line 17, changing the index of mod_info from 1 to -1 seems to work with the default vanilla and vanilla+ packs. 

Would close the issue, but the change does not work with the pack that I created.  Going to try making a simpler one.

**Comment by Riunix** [comment]
The program had problems with files that contained multiple underscores.
I change the code between the comment on cache.py:71 and the line `
        os.remove(name+".zip")`
to
`name = mods[0][0]`
` for word in mods[0][1:]:`
`     name += "_" + word`

Seems to work fine now.

Edit: Unsure how to do the formatting for it, but the last line should be indented

**Comment by Dentosal** [comment]
Hi! Thanks for reporting the issue. I am currently working on a big refactoring, and I will hopefully fix this while doing so.

**Comment by Dentosal** [comment]
Hopefully fixed by d5b4d22. Please reopen if the issue still exists.
